### ISSUE TITLE
what-if: expose yaru-colors in appearance panel

### ISSUE THREAD

**Issue by Muqtxdir** [Jannomag/Yaru-Colors#132]
hi,

after having discussions with @Jannomag. It seemed that it would benefit a lot of ubuntu users to integrate ***Yaru colors*** with [what if PPA](https://launchpad.net/~muqtxdir-m/+archive/ubuntu/what-if).

_Note: This is only targeted toward people who use ubuntu-desktop_ 

### TO-DO:

- [ ] review what colors to include and which to exlude to avoid conflicts.
- [ ] expose colors as accent-colors in Appearance panel.
- [ ] add install instructions.
- [ ] backport to 20.04
- [ ] port to 21.10
- [ ] port to 22.04

### early demo:

https://user-images.githubusercontent.com/54065734/151672041-0fa21832-29ce-4320-b49e-6cde58be86d6.mp4

### Fixes: #129, #124, #122, #120, #111

Thanks!

**Comment by Muqtxdir** [comment]
**Yaru-colors** is now packaged for [`what -if PPA`]( https://launchpad.net/~muqtxdir-m/+archive/ubuntu/what-if) for ubuntu 21.10.

#### install:
```bash
sudo add-apt-repository ppa:muqtxdir-m/what-if
sudo apt update
sudo apt upgrade
```

#### uninstall:
```bash
sudo apt install ppa-purge && sudo ppa-purge ppa:muqtxdir-m/what-if
```

**Comment by Mek101** [comment]
> Note: This is only targeted toward people who use ubuntu-desktop
?

Also, I would like to have a confirm by @Jannomag or somebody with push privileges, if possible

**Comment by Jannomag** [comment]
> > Note: This is only targeted toward people who use ubuntu-desktop
> 
> 
> 
> ?
> 
> 
> 
> Also, I would like to have a confirm by @Jannomag or somebody with push privileges, if possible
> 
> 

I can confirm whatever @Muqtxdir says...

Tbh, I stopped working on Yaru-Colors since the current changes on Ubuntu-Desktop and also Gnome will brake the limits of my knowledge. 
@Muqtxdir is collaborator of this repo and he has my permission to do whatever he wants with this project.

Maybe in the future I will be back again, but no promises.

**Comment by Muqtxdir** [comment]
> > Note: This is only targeted toward people who use ubuntu-desktop
> 
> ?
> 
> Also, I would like to have a confirm by @Jannomag or somebody with push privileges, if possible

I decided to only target ubuntu-desktop, because it's the one I use and most of yaru-colors users are on. I can't make out time to test and build for all the colors provided by yaru-colors. So I mentioned Jan that I'd use around 7 other colors mentioned above to keep it specific for `what if PPA` and integrate it closely with `GNOME-Shell` (_you wouldn't need user themes extension for changing GNOME Shell themes_ ) and `gnome-control-center`

If someone else is interested in covering all the yaru-colors and keeping it distribution agnostic, they can make PR for that : )

**Comment by Mek101** [comment]
@Muqtxdir the tool I wrote to manage all the combinations only supports creating manifests from the releases. Could you make one?

**Comment by Muqtxdir** [comment]
done, please take look at the [releases page](https://github.com/Jannomag/Yaru-Colors/releases)

**Comment by Mek101** [comment]
Should be updated. Could you check if everything works for you?

**Comment by Muqtxdir** [comment]
> Should be updated. Could you check if everything works for you?

It looks like there are two branches for themes, why are there multiple branches?
```
   1) runtime/org.gtk.Gtk3theme.Yaru-Blue-dark/x86_64/stable           <----It looks you updated this 
   2) runtime/org.gtk.Gtk3theme.Yaru-Blue-dark/x86_64/3.22
```

**Comment by Mek101** [comment]
I "deprecated" the 3.22 branch last year: https://github.com/flathub/org.gtk.Gtk3theme.Yaru-Amber/commit/cd95b57b2541bc2c7cb49ce2b545e27faf9a86f8
Mostly because I didn't really see the point of having multiple branches for what, at the end, is a Gtk 3 theme
